# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94a241b386acb24dae351d1787656ff32088057be72ecf62111fa151755f71e2ba0fe1eaab0205fd1f77c88434bb3c5396b24816f33025a0f8b9d761a335daeb

test:
  secret_key_base: c91d96603f8347b1ed2651736a4f81f8f2e749cc8b0afbf1000db45817389f590a8b6f05932a51c7d4164c8d35b137716c7a0eb161ad4b87636a0a2f8f6fd415

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
